API_KEY = None
BASE_URL = None

EMBEDDING_MODEL = "Qwen/Qwen3-Embedding-8B"
EMBEDDING_API_KEY = None
EMBEDDING_BASE_URL = None

TAVILY_API_KEY = None

DEFAULT_MODEL = "gpt-5"
DEFAULT_MODEL_PROVIDER = "openai"


MAX_PLANS = 3
PLAN_MODEL = None
PLAN_MODEL_SETTING = {}
PLAN_MAX_AGENT_ITERS = 60

PLAN_AGGREGATION_MODEL_SETTING = {}

DATA_CHECK_MODEL_SETTING = {"reasoning_effort": "low"}
DATA_CHECK_MAX_AGENT_ITERS = 60

MAX_PLAN_DEBUG_ROUND = 2